version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  backend-dev:
    build:
      context: .
      target: build
    command: ./mvnw spring-boot:run
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: db-se-doce-fosse
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
