version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  backend-dev:
    build:
      context: .
      target: build
    command: ./mvnw spring-boot:run
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
