spring.application.name=backend

spring.datasource.url=jdbc:postgresql://postgres:5432/db-se-doce-fosse
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.liquibase.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.data.mongodb.uri=mongodb://mongouser:mongopassword@mongo:27017/db-se-doce-fosse?authSource=admin
spring.data.mongodb.database=db-se-doce-fosse

api.security.token.secret=U29tZVN1cGVyU2VjcmV0S2V5MTIzIQ==